name: flake8
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "tools/*.py"
      - ".github/workflows/flake8.yml"
  push:
    branches:
      - '**'
    paths:
      - "tools/*.py"
      - ".github/workflows/flake8.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Lint with flake8
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba # v2.3.0
        with:
          ignore: "E265,E266,E501,E402"
          max-line-length: "120"
